<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>

</body>

</html>
<script>  
  // 异步
  // try {
  //   setTimeout(() => {
  //     throw Error("unexpected operation happen...")
  //   }, 100);
  // }
  // catch (e) {
  //   console.log(e.message)
  // }
  // window.onerror = function (message, source, lineno, colno, error) {
  //   console.log('message', message);
  //   // Do something you like.
  // }
  /**
   * catch捕获到异常 如果没有捕获呢
   * */
  // new Promise(function (resolve, reject) {
  //   setTimeout(reject, 0)
  // }).catch(function (e) {
  //   console.log("catch")
  //   return "bingo"
  // }).then(function (x) {
  //   console.log(x)
  // })

  new Promise(function (resolve, reject) {
    setTimeout(reject, 0)
  }).then(function (x) {
    console.log(x)
  })

  window.addEventListener("unhandledrejection", function (e) {
    console.log('2', e);
    // Event新增属性
    // @prop {Promise} promise - 状态为rejected的Promise实例
    // @prop {String|Object} reason - 异常信息或rejected的内容

    // 会阻止异常继续抛出，不让Uncaught(in promise) Error产生
    e.preventDefault()
  })

</script>